Update navbar icon when add to cart
8bitzz/COSC2101 pull request #79
Opened 2021-08-16 12:09 UTC by hongnguyen0112

**Description**
Implement add movie to cart when click "Add to cart" in movie detail page
Cart successfully created and movie successfully added

**Acceptance criteria**
When user clicks "Add to cart" to number of movie should +1 and display in the cart icon

**Bugs**
Number of movies is not automatically changed (Need to go back to homepage or refresh to change the number)
Some movie can not be add to cart (Error Code: 500 (Internal Server Error))
When log out, number of movie can not reset to 0

2021-08-17 14:05 UTC, hongnguyen0112 commented
**Description**
Implement add movie to cart when click "Add to cart" in movie detail page
Cart successfully created and movie successfully added
Cart icon only appear when user is already logged in

**Acceptance criteria**
When user clicks "Add to cart" to number of movie should +1 and display in the cart icon
When user not logged in, cart item is hidden
When user logged in, cart item appear
When user log out and log in again, number of item should remain the same

2021-08-17 14:15 UTC, DanCat6300 approved these changes

2021-08-17 14:50 UTC, NghiaTranUIT requested changes
Thanks for your Pull Request, but I've discovered few bugs:

- Bug 1: When the user is logged out, there is a lot of error in console log => Should not fetch a cart if user is not logged in
- Bug 2: Click on Add to Cart button on Movie detail doesn't work => Should redirect to Login if user is not logged in.
<img width="1674" alt="2" src="https://user-images.githubusercontent.com/5878421/129748383-42addaf3-a54b-43b1-8e74-4d6b2f77065e.png">

- Bug 3: Add to cart should work in the main page.
<img width="1653" alt="1" src="https://user-images.githubusercontent.com/5878421/129748226-3da9f164-1fed-44b1-b2cd-57948bfae754.png">

2021-08-17 14:50 UTC, NghiaTranUIT commented on frontend/src/components/movieList/Details.jsx
> +    var mongodb = require('mongodb');
Can you elaborate on why do we have `mongodb` here?

2021-08-17 14:50 UTC, NghiaTranUIT commented on frontend/package.json
> +    "mongoose": "^5.13.7",
`mongoose` should not be used on Front-End. It's exclusively for Backend.

2021-08-17 15:12 UTC, hongnguyen0112 commented on frontend/package.json
> +    "mongoose": "^5.13.7",
There was a missunderstanding while we were working on the code. We installed it but we didn't use it in the code.

2021-08-17 15:13 UTC, hongnguyen0112 commented on frontend/src/components/movieList/Details.jsx
> +    var mongodb = require('mongodb');
It was redundant, I will delete it. Since we tried to parse from String to ObjectId. But it was a misunderstanding.

2021-08-17 15:14 UTC, NghiaTranUIT commented on frontend/package.json
> +    "mongoose": "^5.13.7",
so, please uninstall it from our npm package 👍

2021-08-17 15:17 UTC, hongnguyen0112 commented on frontend/package.json
> +    "mongoose": "^5.13.7",
Uninstalled and pushed again

2021-08-17 15:19 UTC, hongnguyen0112 commented on frontend/package.json
> +    "mongoose": "^5.13.7",
I fixed 3 bugs you mentioned. Can you review it again?

2021-08-18 14:00 UTC, NghiaTranUIT approved these changes

2021-08-18 14:00 UTC, merged